//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace autocomplete
{
    using System;
    using System.Collections.Generic;
    
    public partial class nepali
    {
        public string न_म { get; set; }
        public string ठ_ग_न_ { get; set; }
    }
}
